### PR TITLE
Encrypt network sync streams

### PR DESCRIPTION
**Pull request by noffle**
This uses libsodium's streaming chacha20 symmetric key encryption scheme.

### CODE REVIEW

**Comment by noffle** [comment]
Debugging a flaky test failure where hypercore is causing a timeout..

**Comment by noffle** [comment]
Tracked the issue down to https://github.com/mafintosh/hypercore/pull/239. I'll merge once I can incorporate the fix & tests pass.

**Comment by noffle** [comment]
Ok, should be good to go!

cc @gmaclennan

**Comment by noffle** [comment]
Blocked on https://github.com/mafintosh/hypercore/pull/241 for this.

**Comment by gmaclennan** [comment]
Just taking a quick look at this, switching `projectKey` to be an option on the instance (as opposed to an _arg_ for the sync function) will require a refactor when start supporting multiple projects. I guess we could just change the API now, then change it to something when we add multi-project support, what do you think?

**Comment by gmaclennan** [comment]
Do you think we will need to move towards using the [Noise Protocol](http://noiseprotocol.org) like hypercore in the future? If so should we wait to deploy this? I know this depends on what we do for WCMC, and if it were not a disconnected p2p system I would say let's just go ahead, but I'm wondering about forward compatibility and update challenges. Let's discuss on our next tech checkin.

**Comment by noffle** [comment]
> switching projectKey to be an option on the instance (as opposed to an arg for the sync function) will require a refactor when start supporting multiple projects.

What refactor will it require?

> Do you think we will need to move towards using the Noise Protocol like hypercore in the future?

I'm not sure why hypercore switched to NOISE, but I just asked on the #dat irc! My understanding is that they're using xchacha via NOISE, which is the same crypto scheme being introduced by this PR. As far as I know, this symmetric encryption scheme should be sufficient for our purposes.

**Pull request closed without merging**
