### PR TITLE
feat: expose device{Name,Type} on peers api

### PR DESCRIPTION
**Pull request by noffle**
This was the easiest way to expose the `deviceName` and `deviceType` fields, but it feels at odds with the existing `type` field. It feels weird to have two `device*` fields that are only present when `type === 'wifi'`.

We could make the types `file` and `device`, and have `device.name` and `device.type` fields. It'd be a bit more clear that the `device` field would only be present when the type is `'device'`.

### CODE REVIEW

**Comment by gmaclennan** [comment]
Hey we already have the name in there, somehow. This is the Type I am using on mobile for the peers, which I got from reading through the code:

```
export type ServerPeer = {
  id: string,
  name: string,
  // Host address for peer
  host: string,
  // Port for peer
  port: number,
  state?:
    | {|
        topic: "replication-progress",
        message: {|
          db: {| sofar: number, total: number |},
          media: {| sofar: number, total: number |}
        |},
        lastCompletedDate?: number
      |}
    | {|
        topic: "replication-wifi-ready",
        lastCompletedDate?: number
      |}
    | {|
        topic: "replication-complete",
        // The time of completed sync in milliseconds since UNIX Epoch
        message: number,
        lastCompletedDate?: number
      |}
    | {|
        topic: "replication-error",
        // Error message
        message: string,
        lastCompletedDate?: number
      |}
    | {|
        topic: "replication-started",
        lastCompletedDate?: number
      |}
};
```

**Comment by noffle** [comment]
Oh, [you're right](https://github.com/digidem/mapeo-core/blob/master/sync.js#L343)! I'll update this to just set `deviceType`.

**Comment by gmaclennan** [comment]
Thoughts on both name and deviceType being `null` or `undefined` if they are not known? Testing against a string always seems flakey (thinking the front-end might want to deal with unknown names in its own way)

**Comment by noffle** [comment]
@gmaclennan That's fine, if it makes things easier for you.

**Pull request merged**
